import { LitElement, TemplateResult } from 'lit';
import '@material/mwc-list';
import '@material/mwc-list/mwc-list-item';
import '@material/mwc-icon-button';
import '@material/mwc-button';
import '@openscd/oscd-filtered-list';
import './foundation/components/oscd-textfield.js';
import './foundation/components/action-filtered-list.js';
import type { OscdTextfield } from './foundation/components/oscd-textfield.js';
/** An editor [[`plugin`]] for editing the `DataTypeTemplates` section. */
export default class TemplatesPlugin extends LitElement {
    /** The document being edited as provided to plugins by [[`OpenSCD`]]. */
    doc: XMLDocument;
    editCount: number;
    selectedLNodeType: Element | null | undefined;
    selectedDOType: Element | null | undefined;
    selectedDAType: Element | null | undefined;
    selectedEnumType: Element | null | undefined;
    get dataTypeTemplate(): Element | null;
    lNodeTypeDiff: boolean;
    lNodeTypeInputs?: OscdTextfield[];
    doTypeDiff: boolean;
    doTypeInputs?: OscdTextfield[];
    daTypeDiff: boolean;
    daTypeInputs?: OscdTextfield[];
    enumTypeDiff: boolean;
    enumTypeInputs?: OscdTextfield[];
    private onLNodeTypeInputChange;
    private onSaveLNodeType;
    private onDOTypeInputChange;
    private onSaveDOType;
    private onDATypeInputChange;
    private onSaveDAType;
    private onEnumTypeInputChange;
    private onSaveEnumType;
    private dispatchEditEvent;
    private dispatchCreateEvent;
    private openEnumTypeWizard;
    private openDATypeWizard;
    private openDOTypeWizard;
    private selectReferencedChild;
    private openLNodeTypeWizard;
    private renderEnumTypeChildrenList;
    private renderEnumTypeList;
    private renderDATypeChildrenList;
    private renderDATypeList;
    private renderDOTypeChildrenList;
    private renderDOTypeList;
    private renderLNodeTypeChildrenList;
    private renderLNodeTypeList;
    render(): TemplateResult;
    static styles: import("lit").CSSResult;
}
