import { LitElement, TemplateResult } from 'lit';
import '@material/mwc-checkbox';
import '@material/mwc-formfield';
import '@material/mwc-list/mwc-list-item-base';
import '@material/mwc-textfield';
import { List } from '@material/mwc-list';
import type { TextField } from '@material/mwc-textfield';
import type { ListItemBase } from '@material/mwc-list/mwc-list-item-base';
export declare function redispatchEvent(element: LitElement, event: Event): boolean;
export declare class ActionFilteredList extends LitElement {
    searchFieldLabel?: string;
    disableCheckAll: boolean;
    multi: boolean;
    activatable: boolean;
    get selected(): ListItemBase | ListItemBase[] | null;
    get index(): import("@material/mwc-list").MWCListIndex;
    items: ListItemBase[];
    private get existCheckListItem();
    private get isAllSelected();
    private get isSomeSelected();
    infoList: List;
    listPrimary: List;
    listSecondary: List;
    searchField: TextField;
    private onCheckAll;
    onFilterInput(): void;
    firstUpdated(): void;
    constructor();
    private renderCheckAll;
    render(): TemplateResult;
    static styles: import("lit").CSSResult;
}
